---

  - debug: var=rvars_devportal_clustering_wrapper_index verbosity=1
  - debug: var=rvars_devportal_clustering_peers verbosity=1

  - name: Fail if no clustering peers are specified
    fail: 
      msg: "a List of clustering peers must be specified..."
    when: rvars_devportal_clustering_peers is not defined or (rvars_devportal_clustering_peers | length) == 0

  - name: Create the jvm_params dictionary
    set_fact:
      jvm_params_wrapper_index: "{{ rvars_devportal_clustering_wrapper_index | int }}"
      jvm_params_dict: "{{ jvm_params_dict | default({}) }}"
  
  - name: add new key / value pairs to dict
    set_fact:
      jvm_params_wrapper_index: "{{ jvm_params_wrapper_index | int + 1 }}"
      jvm_params_dict: "{{ jvm_params_dict | combine({item.key: item.value}) }}"
    with_items:
      - {'key': "wrapper.java.additional.{{ jvm_params_wrapper_index }}", 'value': "-Dportal.server.cache.distributed.enabled=true" }      

  - name: Add peers to dictionnary
    set_fact: 
      jvm_params_wrapper_index: "{{ jvm_params_wrapper_index | int + 1 }}"
      jvm_params_dict: "{{ jvm_params_dict | combine ({ 'wrapper.java.additional.' + (jvm_params_wrapper_index | string) : '-Dportal.server.cache.distributed.cluster.peers.' + (peer_index | string) + '=' + item }) }}"
    with_items: "{{ rvars_devportal_clustering_peers }}"
    loop_control:
      index_var: peer_index

  - debug: var=jvm_params_dict verbosity=1

  - import_role: 
      name: configure-jvm-wrapper
    vars:
      configs_action: set-jvm-params
      rvar_wrapper_file: "{{ custom_wrapper_file }}"
      jvm_params: "{{ jvm_params_dict }}"

  - name: cleanup facts
    set_fact:
      jvm_params_dict: {}
      jvm_params_wrapper_index: ""