---

- debug:
    msg: Begin tasks configurations/create.yml

- name: Object type
  debug: var=rvar_devportal_rest_configs_category

- name: Object to create
  debug: var=rvar_devportal_rest_configs_kv_list verbosity=1

- name: fail if mandatory params not specified
  fail:
    msg: "A mandatory param was not defined, cannot do anything."
  when: item is not defined
  with_items:
    - "{{ rvar_devportal_rest_configs_category }}"
    - "{{ rvar_devportal_rest_configs_kv_list }}"

- name: Payload Object
  set_fact:
    _configurations_payload: "{{ _configurations_payload_template }}"
  vars:
    _configs_category: "{{ rvar_devportal_rest_configs_category }}"
    _configs_kv_list: "{{ rvar_devportal_rest_configs_kv_list }}"

- name: Payload Object
  debug: var=_configurations_payload verbosity=1

- name: Update object
  uri:
    url: "{{ _devportal_rest_configurations_basepath }}/{{ rvar_devportal_rest_configs_category }}"
    method: PUT
    user: "{{ rvar_devportal_rest_auth_username }}"
    password: "{{ rvar_devportal_rest_auth_password }}"
    return_content: yes
    force_basic_auth: yes
    validate_certs: "{{ not ( rvar_devportal_rest_no_check_certs | default() | bool ) }}"
    status_code: [200]
    body_format: json
    body: "{{ _configurations_payload | to_json }}"
    timeout: 30
  no_log: "{{ not ( disable_no_log | default(false,true) ) }}"
  register: rest_response_create

- name: Print response
  debug:
    var: rest_response_create
    verbosity: 2
