---

# REST settings
rvar_devportal_rest_scheme: "http"
rvar_devportal_rest_host: "localhost"
rvar_devportal_rest_port: "18101"
rvar_devportal_rest_base_uri: "{{ rvar_devportal_rest_scheme }}://{{ rvar_devportal_rest_host }}:{{ rvar_devportal_rest_port }}/portal"
rvar_devportal_rest_auth_username: someuser
rvar_devportal_rest_auth_password: something
rvar_devportal_rest_apiversion: "v1"
rvar_devportal_rest_base: "{{ rvar_devportal_rest_base_uri }}/rest/{{ rvar_devportal_rest_apiversion }}"
rvar_devportal_rest_no_check_certs: false

# configurations
_devportal_rest_configurations_basepath: "{{ rvar_devportal_rest_base }}/configurations"

## format for 
# _configs_category: one of the valid category string
# _configs_kv_list:
#   - key: key1
#     value: value1
#   - key: key2
#     value: value2
_configurations_payload_template:
  category: "{{ _configs_category }}"
  properties: "{{ _configs_kv_list }}"

# User management
rvar_devportal_rest_objtype_users: "users"
rvar_devportal_rest_objtype_groups: "groups"
rvar_devportal_rest_objtype_teams: "teams"
rvar_devportal_rest_objtype_health: "health"

## update passwords
rvar_devportal_rest_users_selfupdatepassword:
  oldPassword:
  newPassword:
rvar_devportal_rest_users_updatepassword:
  lookup_userid:
    name: ""
  newPassword:

## assign users to groups
rvar_devportal_rest_groups:
  - lookup_id:
      name: group1
    data:
      name: group1
      description: group 1
    permissions:
      consumers: "true"
      providers: "true"
      administrators: "false"
    users:
      lookup_ids:
        - name: user1
  - lookup_id:
      name: group2
    data:
      name: group2
      description: group 2
    permissions:
      consumers: "false"
      providers: "false"
      administrators: "true"
    users:
      lookup_ids:
        - name: user1
        - name: user2
